#!/bin/sh
# chkconfig: 345 99 1
# description: Jetty service
# processname: java

case "$1" in
  start)
    cd /opt/solr/example
    java -Dsolr.solr.home=multicore -Djetty.port={{ port }} -jar start.jar >> /var/log/jetty.log 2>&1 & 
    echo $! > /opt/solr/jetty.pid
    ;;
  stop)
    pid=`cat /opt/solr/jetty.pid`
    kill $pid
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}" 
    exit 1
    ;;
esac
exit 0
